---
title: "Corpus"
output:
    html_document:
        toc: true
        toc_depth: 3
        toc_float: true
        number_sections: true
        theme: cerulean
        highlight: pygments
        code_folding: hide
        fig_width: 9
        fig_height: 3
        css: style.css
params:
    datadir: "./data"
    graphdir: "./graphs"
    macrodir: "./macros"
    sigdir: "./signatures"
---

```{r echo = FALSE, warning=FALSE, message=FALSE}
## https://bookdown.org/yihui/rmarkdown-cookbook/source-script.html
source("analysis.R", local = knitr::knit_global())
MacGen <- LatexMacroGenerator$new(params$macrodir)
```

```{r echo=FALSE, warning=FALSE, message=FALSE, eval=TRUE}
cat("Corpus size: ", length(corpus))
cat("Client size: ", length(client))

summarize_programs_sloc <- function(df, packages, types = c("test", "example", "testthat", "vignette")) {
    df %>%
        filter(package %in% packages) %>%
        filter(type %in% types) %>%
        filter(language %in% c("R", "C/C++ Header", "C", "C++", "Fortran 77")) %>%
        mutate(language = case_when(language == "R" ~ "R", TRUE ~ "Native")) %>%
        mutate(type = case_when(type == "testthat" ~ "test", TRUE ~ type)) %>%
        mutate(type = str_to_title(type)) %>%
        group_by(language, type) %>%
        summarize(count = n(), code = sum(code)) %>%
        ungroup()
}
```

# Runnable Code

```{r echo=FALSE, warning=FALSE, message=FALSE, eval=TRUE}
get_relative_program_names <- function(program_names) {
	split_and_join <- function(splits) { 
	    n <- length(splits); 
	    program <- splits[[n - 1]]
	    package <- splits[[n - 2]]
	    type <- splits[[n - 3]]
	    path(type, package, program, ext = "R")
	}
	
	map_chr(path_split(program_names), split_and_join)
}

corpus_programs <- get_relative_program_names(corpus_programs)
client_programs <- get_relative_program_names(client_programs)

all_programs = c(corpus_programs, client_programs)

str(all_programs)

sloc_script %>% pull(package) %>% unique()

sloc_script <-
    sloc_script %>%
    mutate(temp = type, type = package, package = temp) %>%
    mutate(program = path_ext_set(path(type, package, filename), "R")) %>%
    filter(program %in% all_programs)
    
datatable(sloc_script)

runnable_code <-
   add_column(summarize_programs_sloc(sloc_script, corpus), kind = "Corpus", .before = 1) %>%
   bind_rows(add_column(summarize_programs_sloc(sloc_script, client), kind = "Client", .before = 1)) %>%
   mutate(CountName = paste0(kind, type, "Count"),
          CodeName = paste0(kind, type, "Code"))
   
runnable_code %>% show_table()

MacGen$from_vectors(runnable_code$CountName, label_num(runnable_code$count))
MacGen$from_vectors(runnable_code$CodeName, label_num(runnable_code$code))
```

# Package Code

```{r echo=FALSE, warning=FALSE, message=FALSE, eval=TRUE}
package_code <-
   add_column(summarize_programs_sloc(sloc_package, corpus, c("R", "src")), kind = "Corpus", .before = 1) %>%
   bind_rows(add_column(summarize_programs_sloc(sloc_package, client, c("R", "src")), kind = "Client", .before = 1)) %>%
   group_by(kind, language) %>%
   summarize(count = sum(count), code = sum(code)) %>%
   ungroup() %>%
   mutate(CodeName = paste0(kind, language, "Code"))

package_code %>% show_table()

MacGen$from_vectors(package_code$CodeName, label_num(package_code$code))
```

# General Corpus Info

```{r echo=FALSE, warning=FALSE, message=FALSE, eval=TRUE}
str(package_dependency)

CorpusDependencyCount <- 
    package_dependency %>% 
    filter(package %in% corpus) %>%
    pull(client) %>%
    unique() %>%
    length()

MacGen$from_args(CorpusDependencyCount = label_comma()(CorpusDependencyCount))

package_by_dependency <- 
    package_dependency %>%
    filter(package %in% corpus) %>%
    count(package, name = "n") %>%
    arrange(desc(n))

maximum_dependency <- slice(package_by_dependency, 1)

MacGen$from_args(CorpusMaximumDependencyPackage = maximum_dependency$package,
                 CorpusMaximumDependencyCount = label_comma()(maximum_dependency$n))

minimum_dependency <- slice_tail(package_by_dependency)

MacGen$from_args(CorpusMinimumDependencyPackage = minimum_dependency$package,
                 CorpusMinimumDependencyCount = label_comma()(minimum_dependency$n))
```

# Package Functions
```{r echo=FALSE, warning=FALSE, message=FALSE, eval=TRUE}
fun_dist <-
    parameters %>% 
    distinct(pack_name, fun_name) %>%
    filter(pack_name %in% corpus)

pack_fun_count <-
    fun_dist %>%
    count(pack_name, name = "function_count") %>%
    arrange(desc(function_count))
    
    
datatable(pack_fun_count)

maximum_fun <- slice(pack_fun_count, 1)

MacGen$from_args(CorpusMaximumFunctionPackage = maximum_fun$pack_name,
                 CorpusMaximumFunctionCount = label_comma()(maximum_fun$function_count))

CorpusTwentyFivePackageCount <- 
    pack_fun_count %>% 
    filter(function_count <= 25) %>% 
    pull(pack_name) %>% 
    unique() %>% 
    length()

CorpusFiftyPackageCount <- 
    pack_fun_count %>%
    filter(function_count > 500) %>% 
    pull(pack_name) %>% 
    unique() %>% 
    length()

MacGen$from_args(CorpusTwentyFivePackageCount = label_comma()(CorpusTwentyFivePackageCount),
                 CorpusFiveHundredPackageCount = label_comma()(CorpusFiftyPackageCount))
                 
TotalFunctionCount <- nrow(fun_dist)

MacGen$from_args(TotalFunctionCount = label_num(TotalFunctionCount))
                 
fun_dist <-
    fun_dist %>%
    count(pack_name, name = "count") %>%
    mutate(min_range = floor(count/25),
           max_range = ceiling(count/25)) %>%
    mutate(min_range = if_else(min_range == max_range, min_range - 1, min_range)) %>%
    mutate(functions = paste0(min_range * 25 + 1, " - ", max_range * 25)) %>% 
    count(min_range, functions, name = "packages") %>%
    arrange(min_range) %>%
    select(functions, packages)

latex <- pmap_chr(fun_dist, function(functions, packages) {
    paste0(functions, "&", packages, "\\")
})

fun_dist %>% datatable()

cat(latex)
```

# Calls

```{r echo=FALSE, warning=FALSE, message=FALSE, eval=TRUE}

call_dist <-
    parameters %>%
    filter(pack_name %in% corpus) %>%
    group_by(pack_name, fun_name) %>%
    summarize(call_count = first(call_count)) %>%
    ungroup()
    
called_once_packs <-
    call_dist %>%
    filter(call_count == 1) %>%
    pull(pack_name) %>%
    unique() %>%
    length()

TotalCallCount <- sum(call_dist$call_count)

CalledOneFunctionPerc <- label_percent()(nrow(filter(call_dist, call_count == 1)) / TotalFunctionCount)

CalledTenFunctionPerc <- label_percent()(nrow(filter(call_dist, call_count > 10)) / TotalFunctionCount)

MacGen$from_args(TotalCallCount = label_num(TotalCallCount, 1),
                 CalledOneFunctionPerc = latex_sanitize(CalledOneFunctionPerc),
                 CalledTenFunctionPerc = latex_sanitize(CalledTenFunctionPerc))
    
call_dist <-
    call_dist %>%
    count(call_count, name = "fun_count") %>%
    arrange(desc(fun_count)) %>%
    mutate(cumperc = round(100 * cumsum(fun_count) / sum(fun_count), 2))
    
datatable(call_dist)

call_dist_plot <-
    call_dist %>%
    mutate(call_count = if_else(call_count <= 10, as.character(call_count), "> 10")) %>%
    count(call_count, wt = fun_count, name = "fun_count") %>%
    mutate(relative_fun_count = fun_count/sum(fun_count))
    
datatable(call_dist_plot)

total_function_count <- sum(call_dist_plot$fun_count)

call_dist_plot <-
    call_dist_plot %>%
    ggplot(aes(call_count, relative_fun_count)) + 
    geom_col(fill = "black") +
    scale_y_continuous(sec.axis = sec_axis(~ . * total_function_count,
                                           labels = label_number_si()),
                       labels = label_percent()) +
    scale_x_discrete(limits = c(1:10, "> 10")) +
    coord_flip()+
    labs(x = "Calls", y = "Functions")


save_graph(call_dist_plot, "call_dist")

str(parameters)
```

# Parameters

```{r echo=FALSE, warning=FALSE, message=FALSE, eval=TRUE}

TotalArgumentCount <- sum(parameters$call_count)

MacGen$from_args(TotalArgumentCount = label_num(TotalArgumentCount, 1))

corpus_params <-
    parameters %>%
    filter(pack_name %in% corpus)
    
TotalParameterCount <- nrow(distinct(parameters, pack_name, fun_name, formal_pos))

MacGen$from_args(TotalParameterCount = label_num(TotalParameterCount, 1))

str(package_info)

package_info <- 
    package_info %>%
    mutate(funname = paste0("`", funname, "`")) %>%
    select(pack_name = package, fun_name = funname, arity)

param_dist <-
    functions %>%
    distinct(pack_name, fun_name) %>%
    left_join(package_info, by = c("pack_name", "fun_name")) %>%
    filter(!is.na(arity)) %>%
    arrange(desc(arity))

param_dist_raw <-
    param_dist %>%
    mutate(full_name = paste0(pack_name, fun_name)) %>%
    group_by(arity) %>%
    summarize(fun_count = length(unique(full_name))) %>%
    ungroup()
    
datatable(param_dist_raw)

ZeroArityFunctionPerc <- 
    param_dist_raw %>%
    filter(arity == 0) %>%
    pull(fun_count) %>%
    `/`(TotalFunctionCount)

OneArityFunctionPerc <- 
    param_dist_raw %>%
    filter(arity == 1) %>%
    pull(fun_count) %>%
    `/`(TotalFunctionCount)

TenArityFunctionPerc <- 
    param_dist_raw %>%
    filter(arity > 10) %>%
    pull(fun_count) %>%
    sum() %>%
    `/`(TotalFunctionCount)
    
FiftyArityFunctionCount <- 
    param_dist_raw %>%
    filter(arity > 50) %>%
    pull(fun_count) %>%
    sum()

MacGen$from_args(ZeroArityFunctionPerc = latex_sanitize(label_percent()(ZeroArityFunctionPerc)),
                 OneArityFunctionPerc = latex_sanitize(label_percent()(OneArityFunctionPerc)),
                 TenArityFunctionPerc = latex_sanitize(label_percent()(TenArityFunctionPerc)),
                 FiftyArityFunctionCount = label_comma()(FiftyArityFunctionCount))

max_arity_function <- slice(param_dist, 1)

MacGen$from_args(MaxArityFunctionName = paste0(max_arity_function$pack_name, "::", str_sub(max_arity_function$fun_name, 2, -2)),
                 MaxArityFunctionParamCount = max_arity_function$arity)

param_dist_summary <-
    param_dist_raw %>%
    mutate(arity = if_else(arity <= 10, as.character(arity), "> 10")) %>%
    count(arity, wt = fun_count, name = "fun_count") %>%
    mutate(relative_fun_count = fun_count/TotalFunctionCount)
    
datatable(param_dist_summary)

param_dist_plot <-
    ggplot(param_dist_summary, aes(arity, relative_fun_count)) + 
    geom_col(fill = "black") +
    scale_y_continuous(sec.axis = sec_axis(~ . * TotalFunctionCount,
                                           labels = label_number_si()),
                       labels = label_percent()) +
    scale_x_discrete(limits = c(0:10, "> 10")) +
    coord_flip()+
    labs(x = "Parameters", y = "Functions")

save_graph(param_dist_plot, "param_dist")
```

```
corpus_argument_type <-
    argument_type %>%
    filter(pack_name %in% corpus) %>%
    count(vararg, missing, arg_type, wt = argument_count, name = "argument_count")

datatable(corpus_argument_type)

package_info <- 
    package_info %>%
    group_by(package, funname) %>%
    summarize(param_count = n()) %>%
    mutate(funname = paste0("`", funname, "`")) %>%
    ungroup()
    
param_dist <-
    functions %>%
    filter(pack_name %in% corpus) %>%
    left_join(package_info, by = c("pack_name" = "package", "fun_name" = "funname")) %>%
    select(pack_name, fun_name, param_count, fun_def)

datatable(param_dist %>% select(!fun_def))

## TODO: not all functions with NA param_count are 0 argument functions


param_dist <-
    param_dist %>%
    mutate(param_count = if_else(is.na(param_count), 0L, param_count))

param_dist %>%
filter(param_count > 50) %>%
select(pack_name, fun_name, param_count) %>%
pmap_chr(function(pack_name, fun_name, param_count) paste0(pack_name, "::", fun_name, "->", param_count)) %>%
print()

param_dist %>%
    group_by(param_count) %>%
    summarize(package_count = length(unique(pack_name)), packages = paste(unique(pack_name), collapse = ",")) %>%
    ungroup() %>%
    datatable()

param_dist <-
    param_dist %>%
    count(param_count, name = "fun_count") %>%
    arrange(desc(fun_count)) %>%
    mutate(cumperc = round(100 * cumsum(fun_count) / sum(fun_count), 2))
    
datatable(param_dist)

cat("Total parameter positions: ", sum(param_dist$param_count * param_dist$fun_count), "\n")

param_dist <-
    param_dist %>%
    mutate(param_count = if_else(param_count <= 10, as.character(param_count), "> 10")) %>%
    count(param_count, wt = fun_count, name = "fun_count") %>%
    mutate(relative_fun_count = fun_count/sum(fun_count))
    
datatable(param_dist)

total_function_count <- sum(param_dist$fun_count)

param_dist_plot <-
    ggplot(param_dist, aes(param_count, relative_fun_count)) + 
    geom_col(fill = "black") +
    scale_y_continuous(sec.axis = sec_axis(~ . * total_function_count,
                                           labels = label_number_si()),
                       labels = label_percent()) +
    scale_x_discrete(limits = c(0:10, "> 10")) +
    coord_flip()+
    labs(x = "Parameters", y = "Functions")

save_graph(param_dist_plot, "param_dist")
```
