---
title: "Reflecting Arguments"
output:
    html_document:
        toc: true
        toc_depth: 3
        toc_float: true
        number_sections: true
        theme: cerulean
        highlight: pygments
        code_folding: hide
        fig_width: 9
        fig_height: 3
        css: style.css
params:
    datadir: "./data"
    graphdir: "./graphs"
    macrodir: "./macros"
---

```{r echo = FALSE, warning=FALSE, message=FALSE}
## https://bookdown.org/yihui/rmarkdown-cookbook/source-script.html
source("analysis.R", local = knitr::knit_global())
MacGen <- LatexMacroGenerator$new(params$macrodir)
```

# Direct

```{r echo = FALSE, warning=FALSE, message=FALSE}
metaprogram_table <-
    metaprogramming %>%
    filter(native_fun %in% c("substitute", ".External(NA)", ".Call(NA)")) %>%
    distinct(source_pack_name, source_fun_name, source_formal_pos) %>%
    rename(pack_name = source_pack_name, fun_name = source_fun_name, formal_pos = source_formal_pos) %>%
    mutate(metaprogram = TRUE)

arg_ref <-
   arg_ref %>%
   left_join(metaprogram_table, by = c("pack_name", "fun_name", "formal_pos")) %>%
   mutate(metaprogram = if_else(is.na(metaprogram), FALSE, metaprogram)) %>%
   filter(!metaprogram) %>%
   select(-metaprogram)

arg_ref %>%
    filter(!transitive) %>%
    count(self_ref_seq, wt = count, name = "count") %>%
    mutate(perc = compute_percentage(count, 2)) %>%
    arrange(desc(perc)) %>%
    datatable()
    
arg_ref %>%
    filter(!transitive) %>%
    distinct(ref_type, pack_name, fun_name, formal_pos, call_expr, count) %>%
    count(ref_type, pack_name, fun_name, formal_pos, call_expr, wt = count, name = "count") %>%
    datatable()
    

total_arg_summary <- 
    arg_ref %>%
    count(pack_name, fun_name, formal_pos, wt = count, name = "count") %>%
    mutate(full_fun = paste0(pack_name, fun_name),
           full_pos = paste0(pack_name, fun_name, formal_pos))
    
MacGen$from_args(RefCountArgumentsTotal = label_num(sum(total_arg_summary$count)),
                 RefCountPackagesTotal = length(unique(total_arg_summary$pack_name)),
                 RefCountFunctionsTotal = length(unique(total_arg_summary$full_fun)),
                 RefCountParametersTotal = length(unique(total_arg_summary$full_pos)))
                 
direct_arg_summary <- 
    arg_ref %>%
    filter(!transitive) %>%
    count(pack_name, fun_name, formal_pos, wt = count, name = "count") %>%
    mutate(full_fun = paste0(pack_name, fun_name),
           full_pos = paste0(pack_name, fun_name, formal_pos))
    
MacGen$from_args(RefCountArgumentsDirect = label_num(sum(direct_arg_summary$count)),
                 RefCountPackagesDirect = length(unique(direct_arg_summary$pack_name)),
                 RefCountFunctionsDirect = length(unique(direct_arg_summary$full_fun)),
                 RefCountParametersDirect = length(unique(direct_arg_summary$full_pos)))
                 
transitive_arg_summary <- 
    arg_ref %>%
    filter(transitive) %>%
    count(pack_name, fun_name, formal_pos, wt = count, name = "count") %>%
    mutate(full_fun = paste0(pack_name, fun_name),
           full_pos = paste0(pack_name, fun_name, formal_pos))
    
MacGen$from_args(RefCountArgumentsTransitive = label_num(sum(transitive_arg_summary$count)),
                 RefCountPackagesTransitive = length(unique(transitive_arg_summary$pack_name)),
                 RefCountFunctionsTransitive = length(unique(transitive_arg_summary$full_fun)),
                 RefCountParametersTransitive = length(unique(transitive_arg_summary$full_pos)))                 
```

# Transitive

```{r echo = FALSE, warning=FALSE, message=FALSE}
transitive_arg_ref <-
    arg_ref %>%
    filter(transitive) %>%
    distinct(source_pack_name, source_fun_name, source_formal_pos,
             pack_name, fun_name, formal_pos)

datatable(transitive_arg_ref)

transitive_arg_count <- 
    arg_ref %>%
    filter(transitive) %>%
    pull(count) %>%
    sum()

cat("Transitive arguments: ", transitive_arg_count)
cat("Transitive positions: ", nrow(transitive_arg_ref))
cat("Transitive functions: ", length(unique(transitive_arg_ref$fun_name)))
cat("Transitive packages: ", length(unique(transitive_arg_ref$pack_name)))
```


# Backtrace

```{r echo = FALSE, warning=FALSE, message=FALSE}
#arg_ref %>%
#    filter(transitive) %>%
#    select(source_pack_name, source_fun_name, source_formal_pos, pack_name, fun_name, formal_pos, backtrace) %>%
#    pmap(function(source_pack_name, source_fun_name, source_formal_pos, pack_name, fun_name, formal_pos, backtrace) {
#        cat(source_pack_name, "\n") 
#        cat(source_fun_name, "\n")
#        cat(source_formal_pos, "\n")
#        cat(pack_name,"\n") 
#        cat(fun_name, "\n")
#        cat(formal_pos, "\n")
#        cat(backtrace, "\n")
#    })
```
