---
title: "Side-Effecting Arguments"
output:
    html_document:
        toc: true
        toc_depth: 3
        toc_float: true
        number_sections: true
        theme: cerulean
        highlight: pygments
        code_folding: hide
        fig_width: 9
        fig_height: 3
        css: style.css
params:
    datadir: "./data"
    graphdir: "./graphs"
    macrodir: "./macros"
    sigdir: "./signatures"
---

```{r echo = FALSE, warning=FALSE, message=FALSE}
## https://bookdown.org/yihui/rmarkdown-cookbook/source-script.html
source("analysis.R", local = knitr::knit_global())
```

# Overview


```{r echo = FALSE, warning=FALSE, message=FALSE}
str(direct_effects)

str(indirect_effects)

MacGen <- LatexMacroGenerator$new(params$macrodir)
```

# Argument Types

```{r echo = FALSE, warning=FALSE, message=FALSE}

total_promise_count <- sum(argument_type$argument_count)

all_argument_dist <-
    argument_type %>%
    filter(arg_type == "promise") %>%
    mutate(expr_type = str_to_title(expr_type)) %>%
    mutate(expr_type = case_when(expr_type == "Promise" ~ "Promise",
                                 expr_type == "Language" ~ "Call",
                                 expr_type == "Symbol" ~ "Symbol",
                                 TRUE ~ "Value")) %>%
    count(expr_type, wt=argument_count, name = "argument_count") %>%
    mutate(all_perc = round(100 * argument_count / total_promise_count, 2)) %>%
    arrange(desc(all_perc)) %>%
    select(expr_type, all_perc)

se_argument_dist <-
     direct_effects %>%
     mutate(expr_type = str_to_title(expr_type)) %>%
     mutate(expr_type = case_when(expr_type == "Promise" ~ "Promise",
                                  expr_type == "Language" ~ "Call",
                                  expr_type == "Symbol" ~ "Symbol",
                                  TRUE ~ "Value")) %>%
     count(expr_type, wt= argument_count, name = "argument_count") %>%
     mutate(se_perc = round(100 * argument_count / total_promise_count, 2)) %>%
     arrange(desc(se_perc)) %>%
     select(expr_type, se_perc) %>%
     add_row(expr_type = "Value", se_perc= 0)
    
argument_dist <- 
    all_argument_dist %>%
    left_join(se_argument_dist, by = "expr_type")

datatable(argument_dist)

argument_dist %>%
pmap_chr(function(expr_type, all_perc, se_perc) {
    paste(expr_type, as_perc(all_perc), as_perc(se_perc), sep = "&")
}) %>%
paste(collapse = "\\\\\n") %>%
cat()
```

# Table

```{r echo = FALSE, warning=FALSE, message=FALSE}
metaprogram_table <-
    metaprogramming %>%
    filter(native_fun %in% c("substitute", ".External(NA)", ".Call(NA)")) %>%
    distinct(source_pack_name, source_fun_name, source_formal_pos) %>%
    rename(pack_name = source_pack_name, fun_name = source_fun_name, formal_pos = source_formal_pos) %>%
    mutate(metaprogram = TRUE)
    
indirect_effects <-
   indirect_effects %>%
   left_join(metaprogram_table, by = c("pack_name", "fun_name", "formal_pos")) %>%
   mutate(metaprogram = if_else(is.na(metaprogram), FALSE, metaprogram)) %>%
   filter(!metaprogram) %>%
   select(-metaprogram)
   
direct_effects <-
   direct_effects %>%
   left_join(metaprogram_table, by = c("pack_name", "fun_name", "formal_pos")) %>%
   mutate(metaprogram = if_else(is.na(metaprogram), FALSE, metaprogram)) %>%
   filter(!metaprogram) %>%
   select(-metaprogram)

direct_effect_summary <-
   direct_effects %>%
   mutate(full_fun = paste0(pack_name, fun_name),
          full_pos = paste0(pack_name, fun_name, formal_pos)) %>%
   group_by(pack_name, full_fun, full_pos) %>%
   summarize(argument_count = sum(argument_count)) %>%
   ungroup()

MacGen$from_args(EffectCountArgumentsDirect = label_num(sum(direct_effect_summary$argument_count)),
                 EffectCountPackagesDirect = length(unique(direct_effect_summary$pack_name)),
                 EffectCountFunctionsDirect = length(unique(direct_effect_summary$full_fun)),
                 EffectCountParametersDirect = length(unique(direct_effect_summary$full_pos)))
                 
transitive_effect_summary <-
   indirect_effects %>%
   mutate(full_fun = paste0(pack_name, fun_name),
          full_pos = paste0(pack_name, fun_name, formal_pos)) %>%
   group_by(pack_name, full_fun, full_pos) %>%
   summarize(argument_count = sum(argument_count)) %>%
   ungroup()

MacGen$from_args(EffectCountArgumentsTransitive = label_num(sum(transitive_effect_summary$argument_count)),
                 EffectCountPackagesTransitive = length(unique(transitive_effect_summary$pack_name)),
                 EffectCountFunctionsTransitive = length(unique(transitive_effect_summary$full_fun)),
                 EffectCountParametersTransitive = length(unique(transitive_effect_summary$full_pos)))

total_effect_summary <-
   direct_effects %>%
   bind_rows(indirect_effects) %>%
   mutate(full_fun = paste0(pack_name, fun_name),
          full_pos = paste0(pack_name, fun_name, formal_pos)) %>%
   group_by(pack_name, full_fun, full_pos) %>%
   summarize(argument_count = sum(argument_count)) %>%
   ungroup()

MacGen$from_args(EffectCountArgumentsTotal = label_num(sum(total_effect_summary$argument_count)),
                 EffectCountPackagesTotal = length(unique(total_effect_summary$pack_name)),
                 EffectCountFunctionsTotal = length(unique(total_effect_summary$full_fun)),
                 EffectCountParametersTotal = length(unique(total_effect_summary$full_pos)))
```

# Functions Doing Removals

```{r echo = FALSE, warning=FALSE, message=FALSE}
direct_effects %>%
filter(remove_count != 0) %>%
distinct(pack_name, fun_name, formal_pos) %>%
datatable()
```

# Simplified Effect Sequence

```{r echo = FALSE, warning=FALSE, message=FALSE}
merge_effects <- function(seq) {
    seq %>%
    str_replace_all("(L\\+D\\+)+", "(L+D+)+") %>%
    str_replace_all("(D\\+A\\+)+", "(D+A+)+") %>%
    str_replace_all("(L\\+A\\+)+", "(L+A+)+") %>%
    str_replace_all("(D\\+R\\+)+", "(D+R+)+")
}

effect_seq_table <-
    direct_effects %>%
    mutate(simplified_effect_seq = merge_effects(simplified_effect_seq)) %>%
    count(simplified_effect_seq, wt = argument_count, name = "argument_count")

se_promise_count <- sum(effect_seq_table$argument_count)
non_se_promise_count <- total_promise_count - se_promise_count


effect_seq_table <-
    effect_seq_table %>%
    add_row(simplified_effect_seq = "-", argument_count = non_se_promise_count) %>%
    arrange(desc(argument_count)) %>%
    mutate(perc = round(100 * argument_count / sum(argument_count), 2)) %>%
    mutate(cumperc = cumsum(perc)) %>%
    slice(1:5)

datatable(effect_seq_table)

effect_seq_table %>%
pmap_chr(function(simplified_effect_seq, argument_count, perc, cumperc) {
    paste(simplified_effect_seq, as_perc(perc), sep = "&")
}) %>%
paste(collapse = "\\\\\n") %>%
cat()
```

# Effect Distribution

```{r echo = FALSE, warning=FALSE, message=FALSE}

lookup_table <- 
    direct_effects %>%
    filter(lookup_count != 0) %>%
    summarize(type = "L",
              count = sum(lookup_count),
              arguments = sum(argument_count),
              parameters = length(unique(paste0(pack_name, fun_name, formal_pos, "::"))),
              functions = length(unique(paste0(pack_name, fun_name, "::"))),
              packages = length(unique(paste0(pack_name, "::"))))

define_table <-
    direct_effects %>%
    filter(define_count != 0) %>%
    summarize(type = "D",
              count = sum(define_count),
              arguments = sum(argument_count),
              parameters = length(unique(paste0(pack_name, fun_name, formal_pos, "::"))),
              functions = length(unique(paste0(pack_name, fun_name, "::"))),
              packages = length(unique(paste0(pack_name, "::"))))

assign_table <- 
    direct_effects %>%
    filter(assign_count != 0) %>%
    summarize(type = "A",
              count = sum(assign_count),
              arguments = sum(argument_count),
              parameters = length(unique(paste0(pack_name, fun_name, formal_pos, "::"))),
              functions = length(unique(paste0(pack_name, fun_name, "::"))),
              packages = length(unique(paste0(pack_name, "::"))))

remove_table <-
    direct_effects %>%
    filter(remove_count != 0) %>%
    summarize(type = "R",
              count = sum(define_count),
              arguments = sum(argument_count),
              parameters = length(unique(paste0(pack_name, fun_name, formal_pos, "::"))),
              functions = length(unique(paste0(pack_name, fun_name, "::"))),
              packages = length(unique(paste0(pack_name, "::"))))

error_table <- 
    direct_effects %>%
    filter(error_count != 0) %>%
    summarize(type = "E",
              count = sum(lookup_count),
              arguments = sum(argument_count),
              parameters = length(unique(paste0(pack_name, fun_name, formal_pos, "::"))),
              functions = length(unique(paste0(pack_name, fun_name, "::"))),
              packages = length(unique(paste0(pack_name, "::"))))

effect_dist <-
    bind_rows(lookup_table,
              define_table,
              assign_table,
              remove_table,
              error_table) %>%
    mutate(count = label_number_si(accuracy=0.1)(count),
           arguments = label_number_si(accuracy=0.1)(arguments),
           parameters = label_number_si(accuracy=0.1)(parameters),
           functions = label_number_si(accuracy=0.1)(functions))

datatable(effect_dist)


effect_dist %>%
pmap_chr(function(...) {
    paste(..., sep = "&")
}) %>%
paste(collapse = "\\\\\n") %>%
cat()
```

# Indirect Effects

```{r echo = FALSE, warning=FALSE, message=FALSE}

direct_par_name <- unique(paste0(direct_effects$pack_name, direct_effects$fun_name, direct_effects$formal_pos))
direct_fun_name <- unique(paste0(direct_effects$pack_name, direct_effects$fun_name))
direct_pack_name <- unique(direct_effects$pack_name)

indirect_effect_summary <-
    indirect_effects %>%
    mutate(par_name = paste0(pack_name, fun_name, formal_pos),
           fun_name = paste0(pack_name, fun_name)) %>%
    filter(!(par_name %in% direct_par_name)) %>%
    group_by(type) %>%
    summarize(parameters = length(unique(par_name)),
              functions = length(unique(fun_name)),
              packages = length(unique(pack_name))) %>%
    ungroup() %>%
    arrange(desc(parameters)) %>%
    mutate(parameters = label_number_si(accuracy=0.1)(parameters),
           functions = label_number_si(accuracy=0.1)(functions))
    
datatable(indirect_effect_summary)


indirect_effect_summary %>%
pmap_chr(function(...) {
    paste(..., sep = "&")
}) %>%
paste(collapse = "\\\\\n") %>%
cat()
```
