---
title: "Validation"
output:
    html_document:
        toc: true
        toc_depth: 3
        toc_float: true
        number_sections: true
        theme: cerulean
        highlight: pygments
        code_folding: hide
        fig_width: 9
        fig_height: 3
        css: style.css
params:
    datadir: "./data"
    graphdir: "./graphs"
    macrodir: "./macros"
---

```{r echo = FALSE, warning=FALSE, message=FALSE}
## https://bookdown.org/yihui/rmarkdown-cookbook/source-script.html
source("analysis.R", local = knitr::knit_global())
```

```{r echo = FALSE, warning=FALSE, message=FALSE}
all_programs <- 
    bind_rows(distinct(exitval_raw, type, package, filename),
              distinct(stdout_raw, type, package, filename)) %>%
    distinct()


exitval_raw <-
    exitval_raw %>%
    pivot_longer(cols = c(`lazy-1`, `lazy-2`, `strict`),
                 names_to = "signature",
                 values_to = "exitval")

stdout_raw <-
    stdout_raw %>%
    pivot_longer(cols = c(`lazy-1`, `lazy-2`, `strict`),
                 names_to = "signature",
                 values_to = "stdout")
                 
                 
validation_tab <-
    exitval_raw %>%
    left_join(stdout_raw, by = c("type", "package", "filename", "signature"))
    
lazy_1_validation_tab <-
    validation_tab %>%
    filter(signature == "lazy-1") %>%
    select(-signature) %>%
    rename(lazy_1_exitval = exitval, lazy_1_stdout = stdout)

lazy_2_validation_tab <-
    validation_tab %>%
    filter(signature == "lazy-2") %>%
    select(-signature) %>%
    rename(lazy_2_exitval = exitval, lazy_2_stdout = stdout)

validation_tab <-
    validation_tab %>%
    left_join(lazy_1_validation_tab, by = c("type", "package", "filename")) %>%
    left_join(lazy_2_validation_tab, by = c("type", "package", "filename")) %>%
    mutate(keep = (lazy_1_exitval == 0) & (lazy_1_exitval == lazy_2_exitval) & lazy_2_stdout)
    
datatable(validation_tab %>% slice(1:100))

validation_tab <-
    validation_tab %>%
    mutate(exitval = !is.na(exitval) & exitval == 0 & exitval == lazy_1_exitval,
           stdout = stdout)
           
## remove all programs whose lazy-1 and lazy-2 don't match
validation_tab <-
    validation_tab %>%
    mutate(exitval = !exitval, stdout = !stdout) %>%
    filter(keep)

baseline_programs <-
    validation_tab %>%
    filter(signature == "lazy-2") %>%
    distinct(type, package, filename) %>%
    nrow()


validation_summary <-
    validation_tab %>%
    group_by(signature, type) %>%
    summarize(#both = sum(exitval & stdout),
              either = sum(exitval | stdout)) %>%
              #exitval = sum(exitval),
              #stdout = sum(stdout)) %>%
    ungroup() 
    ##%>%
    ##group_by(signature) %>%
    ##mutate(type = "total", 
    ##       both = sum(both),
    ##       either = sum(either),
    ##       exitval = sum(exitval),
    ##       stdout = sum(stdout)) %>%
    ##ungroup()
    
validation_summary %>%
datatable()


validation_summary <-
    validation_summary %>%
    group_by(signature) %>%
    mutate(either_perc = round(100 * either / sum(either), 2)) %>%
           #both_perc = round(100 * both / baseline_programs, 2),
           #exitval_perc = round(100 * exitval / baseline_programs, 2),
           #stdout_perc = round(100 * stdout / baseline_programs, 2)) %>%
    ungroup()
    
total_validation_summary <-
    validation_summary %>%
    group_by(signature) %>%
    summarize(type = "total", 
              either = sum(either),
              either_perc = round(100 * either / baseline_programs, 2)) %>%
    ungroup()
    
validation_summary <-
    validation_summary %>%
    bind_rows(total_validation_summary) %>%
    mutate(either_perc = as_perc(either_perc)) %>%
           ##both_perc = as_perc(both_perc),
           ##exitval_perc = as_perc(exitval_perc),
           ##stdout_perc = as_perc(stdout_perc)) %>%
    mutate(signature = str_replace(signature, fixed("signature"), ""),
           signature = str_replace(signature, fixed("force"), "U"),
           signature = str_replace(signature, fixed("effect"), "E"),
           signature = str_replace(signature, fixed("reflection"), "R")) %>%
    mutate(failure = paste(either, either_perc, sep = "&")) %>%
    select(-either, -either_perc) %>%
    filter(!(signature %in% c("lazy-1", "lazy-2"))) %>%
    pivot_wider(names_from = "type",
                values_from = "failure") %>%
    mutate(order = 4 * str_detect(signature, fixed("-U")) +
                   2 * str_detect(signature, fixed("-E")) + 
                   1 * str_detect(signature, fixed("-R"))) %>%
    arrange(order) %>%
    select(order, signature, total) #test, vignette, example, testthat, total)
    

validation_summary %>% datatable()

cat(nrow(all_programs))
cat(baseline_programs)

header <- colnames(validation_summary)

header_latex <- 
    paste(map_chr(header[3:length(header)], function(h) paste0("\\multicolumn{2}{c}{\\textbf{", h, "}}")), collapse = "&")
      
header_latex <- paste0("\\#&", "\\textbf{Configuration}&", header_latex)

body_latex <-
validation_summary %>%
pmap_chr(function(order, signature, ...) {
     
     ##signature <-
     ##    signature %>%
     ##    str_replace_all("[+](.)", "\\\\color{green}{+}&") %>%
     ##    str_replace_all("[-](.)", "\\\\color{red}{-}&") %>%
     ##    str_remove_all("&$")

     signature <- paste0("$", signature, "$")
     res <- paste(order, signature, ..., sep = "&")
})


c(header_latex, body_latex) %>%
paste(collapse = "\\\\\n") %>%
cat()
```
