---
title: "Varargs"
output:
    html_document:
        toc: true
        toc_depth: 3
        toc_float: true
        number_sections: true
        theme: cerulean
        highlight: pygments
        code_folding: hide
        fig_width: 9
        fig_height: 3
        css: style.css
params:
    datadir: "./data"
    graphdir: "./graphs"
    macrodir: "./macros"
    sigdir: "./signatures"
---

```{r echo = FALSE, warning=FALSE, message=FALSE}
## https://bookdown.org/yihui/rmarkdown-cookbook/source-script.html
source("analysis.R", local = knitr::knit_global())
MacGen <- LatexMacroGenerator$new(params$macrodir)
```

```{r echo = TRUE, warning=FALSE, message=FALSE}
VarargParameterCount <- 
    parameters %>%
    filter(vararg) %>%
    distinct(pack_name, fun_name, formal_pos) %>%
    nrow()

VarargFunctionCount <- 
    parameters %>%
    filter(vararg) %>%
    distinct(pack_name, fun_name) %>%
    nrow()

VarargPackageCount <- 
    parameters %>%
    filter(vararg) %>%
    distinct(pack_name) %>%
    nrow()
    
MacGen$from_args(VarargParameterCount = label_num(VarargParameterCount, 1),
                 VarargFunctionCount = label_num(VarargFunctionCount, 1),
                 VarargPackageCount = VarargPackageCount)
```
